all:
  children:
    zabbix:
      hosts:
        zbx.cringerlabs.local:
    ipa:
      hosts:
        ipa.cringerlabs.local:
    foreman:
      hosts:
        foreman.cringerlabs.local:
    elk:
      hosts:
        elk.cringerlabs.local:
    tower:
      hosts:
        tower.cringerlabs.local:
    gitlab:
      hosts:
        gitlab.cringerlabs.local:
    mysql:
      children:
        proxy:
          hosts:
            haprx.cringerlabs.local:
        databases:
          hosts:
            mysql01.cringerlabs.local:
            mysql02.cringerlabs.local:
    swarm:
      hosts:
        docker01.cringerlabs.local:
        docker02.cringerlabs.local:
        docker03.cringerlabs.local:
    kubernetes:
      children:
        k8smaster:
          hosts:
            k8s-01.cringerlabs.local:
        k8snodes:
          hosts:
            k8s-01.cringerlabs.local:
            k8s-02.cringerlabs.local:
            k8s-03.cringerlabs.local:
    jenkins:
      hosts:
        jenkins.cringerlabs.local:
        
