---
- name: BASHRC - Adding Logging bashrc file
  blockinfile:
    path: /etc/bashrc
    block: |
      #
      # Adicionando comandos no rsyslogd
      export PROMPT_COMMAND='history -a >(tee -a ~/.bash_history | logger -p local6.debug -t "$USER[$$] $SSH_CONNECTION")'

- name: SYSLOG - Adding bash commands rsyslog
  copy:
   src: bash.conf
   dest: /etc/rsyslog.d/bash.conf
  notify:
  - "Restart rsyslog"

