---   
- name: Install Repo Zabbix 5.0
  yum:
    name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
    state: present

- name: Zabbix - Installing Agent
  yum:
    name: zabbix-agent
    state: latest

- name: Zabbix - Copy zabbix config file
  template: 
    src: zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf

- name: Firewall - Open Port 10051/TCP
  firewalld:
    port: 10051/tcp
    permanent: yes
    immediate: yes 
    state: enabled

- name: Zabbix - Enabling on boot/Restart
  service:
    name: zabbix-agent
    enabled: yes
  notify: 
    - "Restart zabbix-agent"
