---   
- name: Zabbix - Installing
  yum:
    name: zabbix-agent
    state: latest

- name: Zabbix - Copy zabbix config file
  template: 
    src: zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf

- name: Firewall - Open Port 10051/TCP
  firewalld:
    port: 10051/tcp
    permanent: yes
    immediate: yes 
    state: enabled

- name: Zabbix - Enabling on boot/Restart
  service:
    name: zabbix-agent
    enabled: yes
  notify: 
    - Restart zabbix-agent
